layer = QgsVectorLayer('Point?crs=EPSG:4326', 'point', 'memory') 
provider = layer.dataProvider()
provider.addAttributes([QgsField('Name', QVariant.String)])
provider.addAttributes([QgsField('ID', QVariant.Int)])
layer.updateFields() 
f = QgsFeature()
p1 = QgsPointXY(78.25, 14.25)
p2 = QgsPointXY(78.25, 14.50)
p3 = QgsPointXY(78.50, 14.50)
p4 = QgsPointXY(78.50, 14.25)
f.setGeometry(QgsGeometry.fromPointXY(p1))
f.setAttributes(['Lower Left',1])
provider.addFeature(f)
f.setGeometry(QgsGeometry.fromPointXY(p2))
f.setAttributes(['Upper Left',2])
provider.addFeature(f)
f.setGeometry(QgsGeometry.fromPointXY(p3))
f.setAttributes(['Upper Right',3])
provider.addFeature(f)
f.setGeometry(QgsGeometry.fromPointXY(p4))
f.setAttributes(['Lower Right',4])
provider.addFeature(f)
layer.updateExtents() 
QgsProject.instance().addMapLayer(layer)
QgsVectorFileWriter.writeAsVectorFormat(layer, "E:/hawarit_documents/creatinglayer/testpoint11.shp", "UTF-8", layer.crs(), "ESRI Shapefile")
path = "E:/hawarit_documents/creatinglayer/testpoint11.shp.shp"
layerfile = QgsVectorLayer(path, "test point", "ogr")
QgsProject.instance().addMapLayer(layerfile)